config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # devise
  devise_for :users
  devise_scope :users do
    get  'users/admin_new' => 'users#admin_new'
    post 'users/admin_create' => 'users#admin_create'
  end

  # get 'stock/:id/buy' => 'stocks#buy_stock', as: 'stock_buy'
  get 'admin' => 'users#index', as: 'users_admin'
  get 'stocks' => 'stocks#index'
  resources :users, only: [:index, :show, :update, :destroy, :edit]
  # transactions
  get 'transactions/buy' => 'transactions#buy'
  get 'transactions/:id/sell' => 'transactions#sell', as: "transactions_sell"
  resources :transactions, only: [:create, :destroy]
  #user wallet
  get 'user_wallet/deposit' => 'user_wallet#deposit', as: 'user_deposit'
  get 'user_wallet/withdraw' => 'user_wallet#withdraw', as: 'user_withdraw'
  resources :user_wallet, only: [:create]
  #user history
  get 'user_history' => 'pages#history'
  #error 404
  get '*path' => 'pages#not_found'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_admin_mail
  after_create :send_user_mail
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :user_histories
  has_many :pendings
  
  enum role: [:trader, :admin]
  after_initialize :set_default_role if :new_record?
  def set_default_role
    self.role ||= :user
  end

  def active_for_authentication? 
    super && approved?
  end 
    
  def inactive_message 
    approved? ? super : :not_approved
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if recoverable.persisted?
      if recoverable.approved?
        recoverable.send_reset_password_instructions
      else
        recoverable.errors.add(:base, :not_approved)
      end
    end
    recoverable
  end

  #MAILERS
  def send_admin_mail
    AdminMailer.new_user_waiting_for_approval(email).deliver
  end

  def send_user_mail
    UserMailer.user_message_approval(email).deliver
  end
  

end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController

    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
      @users_not_approved = User.where(approved: false)
      @users_approved = User.where(approved: true, role: "trader")
  end

  def show
    check_if_exist = UserHistory.where(user_id: params[:id]).order(created_at: :desc)
    if check_if_exist.present?
      @user_history = check_if_exist
    end
  end

  def admin_new
    @user = User.new
  end

  def admin_create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "User was successfully created."}
      else
        format.html { render :admin_new, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        if @user.approved?
          UserMailer.user_message_approved(@user.email).deliver
        end
        format.html { redirect_to users_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.html { redirect_to users_path, notice: "User was successfully deleted" }
      end
    end
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :approved)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_new.html.erb
<div class="container d-flex justify-content-center align-items-center flex-column h-75 w-50">

  <h1 class="display-5">Create Users</h1>
  <%= form_with model: @user, :html => {:class => "mt-3 w-100 d-flex flex-column align-items-center"}, :url => '/users/admin_create' do |form| %>

    <div class="w-100">
      <%= form.label :email%>
      <%= form.text_field :email, class:"form-control" %>
      <%= @user.errors.full_messages[0] %>
    </div>
    <div class="w-100">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control" %>
      <%= @user.errors.full_messages[1] %>
    </div>
    <div class="w-100 mt-3">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
      <%= @user.errors.full_messages[2] %>
    </div>

    <%= form.submit class: "btn btn-success w-25 mt-3" %>
  <% end %>
    <%= link_to '<Back to Dashboard', users_path, class: "mt-5 align-self-end"%>

</div>

app/views/users/edit.html.erb
<div class="container h-75 d-flex flex-column align-items-center">
  <%= form_with class: "d-flex flex-column justify-content-center w-75", model: @user do |form| %>
  <%= form.label :email %>
  <%= @user.errors.full_messages[0] %>
  <%= form.text_field :email %>
  <%= form.label :approved %>
  <%= form.select :approved, [[true, "true"], [false, "false"]]%>
  <br>
  <%= form.submit class: "btn btn-success w-25 align-self-center"%>
<% end %>
<%= link_to '<Back to Dashboard', users_path, class: "mt-5" %><br>
</div>

app/views/users/index.html.erb
<div class="container d-flex flex-column">
  <h1 class="text-center mt-3 display-3">Welcome, Admininistrator</h1>
  <p class="text-center">There are currently <b><%= User.count - 1 %></b> users in the system</p>

  <h2 class="mt-3 display-5">Users List</h2>
  <table class="table bg-light">
    <tr>
    <th class="col">Email address</th>
    <th class="col">Approval Status</th>
    <th class="col">Details</th>
    </tr>

  <% @users_approved.each do |user| %>
    <tr>
    <td class="col"><%= user.email %></td>
    <td class="col"><%= user.approved %></td>
    <td class="col"><%= link_to 'View details', user_path(user.id), class: "text-decoration-none" %></td>
    </tr>
  <% end %>
    <tr>
      <td class="col">
        <%= link_to 'Add User', users_admin_new_path, class:"btn btn-success align-self-center"%>
      </td> 
    </tr>
  </table>

   <h2 class="mt-4 display-5">Approval List</h2>
  <% if @users_not_approved.length === 0 %>
    <p>Nothing To Approve</p>
  <% else %>
    <table class="table bg-light">
      <tr>
        <th class="col">Email address</th>
        <th class="col">Approval Status</th>
        <th class="col">Details</th>
      </tr>
      <% @users_not_approved.each do |user| %>
        <tr>
          <td class="col"><%= user.email %></td>
          <td class="col"><%= user.approved %></td>
          <td class="col"><%= link_to 'View details', user_path(user.id) %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>

    <%= form.label :email%>
    <%= form.text_field :email %>
    <br>
    <%= form.label :password %>
    <%= form.text_field :password %>
    <br>
    <%= form.submit %>

<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1 class="display-4 mt-3">User Profile</h1>
  <table class="table table-bordered w-auto mt-3">
      <tr>
          <td>User ID</td>
          <td><%= @user.id %></td>
      </tr>
      <tr>
          <td>Email Address</td>
          <td><%= @user.email %></td>
      </tr>
      <tr>
          <td>Approved?</td>
          <td><%= @user.approved? %></td>
      </tr>
      <tr>
          <td>Change Approval Status</td>
          <td><%= link_to 'Edit', edit_user_path(@user.id), class: "btn btn-outline-warning" %></td>
      </tr>
      <tr>
          <td>Delete User</td>
          <td><%= button_to "Delete", user_path, method: :delete, class: "btn btn-outline-danger"%></td>
      </tr>
  </table>

  <h2 class="display-6">Transaction List</h2>
  <% if @user_history.present? %>
  <table class="table table-striped">
  <thead>
  <th>Transaction</th>
  <th>Stock Symbol</th>
  <th>Amount</th>
  <th>Date</th>
  </thead>
  <tbody>
      <% @user_history.each do |history| %>
      <tr>
      
        <td> <%= history.status.titleize %></td>
        <td>
        <% if !history.symbol.nil? %>
          <%= history.symbol %><br>
        <% end %>
        </td>
        <td>$<%= history.amount %></td>
        <td><%= history.created_at %><br></td>
  </tr>
    <% end %>
    </tbody>
  </table>
  <% else %>
    <p>No Transactions Yet</p>
  <% end %>
<%= link_to '<Back to Dashboard', users_path, class: "mt-5" %>

</div>