config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # devise
  devise_for :users
  devise_scope :users do
    get  'users/admin_new' => 'users#admin_new'
    post 'users/admin_create' => 'users#admin_create'
  end

  # get 'stock/:id/buy' => 'stocks#buy_stock', as: 'stock_buy'
  get 'admin' => 'users#index', as: 'users_admin'
  get 'stocks' => 'stocks#index'
  resources :users, only: [:index, :show, :update, :destroy, :edit]
  # transactions
  get 'transactions/buy' => 'transactions#buy'
  get 'transactions/:id/sell' => 'transactions#sell', as: "transactions_sell"
  resources :transactions, only: [:create, :destroy]
  #user wallet
  get 'user_wallet/deposit' => 'user_wallet#deposit', as: 'user_deposit'
  get 'user_wallet/withdraw' => 'user_wallet#withdraw', as: 'user_withdraw'
  resources :user_wallet, only: [:create]
  #user history
  get 'user_history' => 'pages#history'
  #error 404
  get '*path' => 'pages#not_found'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "home#index"
end

app/views/pages/history.html.erb
HISTORY<br>
<br>
<% @histories.each do |history| %>
  Action: <%= history.status %><br>
  Stock Symbol: <%= history.symbol %><br>
  Amount: $<%= number_with_precision(history.amount, precision: 2) %><br>
  DATE: <%= history.created_at %><br>
  <br>
<% end %>

app/views/pages/home.html.erb
<div class="container bg-light">
<div class="bg-light p-5 rounded text-end">
    <h3>Hello, <%= current_user.email.split("@")[0].titleize %>!</h3>
    <p class="lead">Balance: <b>$<%= number_with_precision(current_user.balance, precision: 2) %></b></p>
    <%= link_to 'Deposit', user_deposit_path, class:"btn btn-success" %>
    <%= link_to 'Withdraw', user_withdraw_path, class:"btn btn-warning" %>

  </div>


<%= link_to 'Trade Stocks', stocks_path, class: "btn btn-primary" %>



  <table class="table table-striped table-hover align-middle">
    <thead>
      <tr>
        <th scope="col">Symbol</th>
        <th scope="col">Company</th>
        <th scope="col">Amount</th>
        <th scope="col">Stock:</th>
        <th scope="col">Amount Change</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @pending_stocks.each do |stock| %>
        <tr>
          <td><%= stock.symbol %></td>
          <td></td>
          <td>$<%= stock.amount %></td>
          <td><%= stock.quantity %></td>
          <td>Pending</td>
        </tr>
      <% end %>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.symbol %></td>
          <td><%= transaction.company_name %></td>
          <td>$<%= number_with_precision(transaction.stock_price, precision: 2) %></td>
          <td><%= transaction.stock_quantity %></td>
          <td>

            <% if transaction.stock_price < @quote = @client.quote(transaction.symbol).latest_price.to_f%>
              <span class="badge bg-danger">
                <%= number_with_precision(transaction.stock_price - @client.quote(transaction.symbol).latest_price.to_f, precision: 2)%>
              </span>
            <% elsif transaction.stock_price > @quote = @client.quote(transaction.symbol).latest_price.to_f%>
              <span class="badge bg-success">
                +<%= number_with_precision(transaction.stock_price - @client.quote(transaction.symbol).latest_price.to_f, precision: 2)%>
              </span>
            <%else%>
              <span class="badge bg-secondary">
                <%= number_with_precision(transaction.stock_price - @client.quote(transaction.symbol).latest_price.to_f, precision: 2)%>
              </span>
            <%end%>



          </td>
          <td><%= link_to 'Buy', transactions_buy_path(SS: transaction.symbol), class:"btn btn-success me-1" %><%= link_to "Sell", transactions_sell_path(transaction.id), class:"btn btn-danger" %></td>
 <% end %>
        </tr>

    </tbody>
  </table>
</div>

app/views/pages/not_found.html.erb
<div class="container h-75 d-flex flex-column justify-content-center align-items-center">
<%= image_tag "404 Page Not Found _Isometric.png", class: "img-fluid" %>
<h1>Page not found</h1>
</div>